# Generated by Django 3.1.2 on 2020-11-07 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 13, 37, 49, 849436)),
        ),
    ]
