# Generated by Django 3.1.5 on 2021-01-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='anonymous', max_length=64)),
                ('spent_money', models.IntegerField()),
                ('gems', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.customer')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.gemname')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_money', models.IntegerField()),
                ('gems', models.IntegerField()),
                ('date', models.CharField(max_length=16)),
                ('gem_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.gemname')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.customer')),
            ],
        ),
    ]
