# Generated by Django 3.1.5 on 2021-01-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='gem_name',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Gem',
        ),
        migrations.DeleteModel(
            name='GemName',
        ),
    ]
