# Generated by Django 3.1.5 on 2021-01-16 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0002_auto_20210116_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
