# Generated by Django 3.1.5 on 2021-01-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0003_auto_20210116_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.CharField(max_length=16),
        ),
    ]
